### ISSUE TITLE
Http Sig implementation in Scala

### ISSUE THREAD

**Issue by bblfish** [bspk/httpsig-org#10]
At IETF meeting in London you mentioned you are collecting implementations of  "Signing Http Messages".

Here is the one I have been working on. 

  https://github.com/bblfish/httpsig

The current published version of the library implements version 0.7 of the spec

I am just updating to version 13  of the spec in 
[HTTP Sig PR 12](https://github.com/bblfish/httpSig/pull/12)

It compiles to Java Byte codes and is ready to be used for [Akka](https://akka.io/) and [Http4s](https://http4s.org/) libraries (in Java and JS). I would be interested in extending it to work on nodeJs or java servers.

It is being used on the [Reactive-Solid server](https://github.com/co-operating-systems/Reactive-SoLiD) and on the client in [SolicCtrlApp](https://github.com/bblfish?tab=repositories). Note that neither of these is used in production and are currently more test beds for new ideas.

**Comment by jricher** [comment]
Included in #13
